---
title: "Demo 5 - From Dynamic to Interactive"
output: 
  html_document:
    runtime: shiny
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(readr)
library(ggplot2)
library(dplyr)
library(shiny)
```


Now, we set the filename using a drop-down:

```{r}
data <- list(
  `Game of Thrones` = "./got_avgs.csv",
  `Parks and Rec` = "./pnr_avgs.csv",
  Simpsons = "./simp_avgs.csv"
)

selectInput(
  inputId = "filename", 
  label = h3("Data set"), 
  choices = data, 
  selected = 1)
```

### Responsive table

```{r, message = FALSE}
selectedData <- reactive({
  read_csv(input$filename) %>% 
    select(Series, Season, EpNum = SubEp, 
           OverallEp = TotalEp,
           Episode, Rating = UserRating, 
           Votes = UserVotes)
})
```

Print the first 10 rows of the data as a table:

```{r}
renderTable({
  head(selectedData(), 10)
})
```

### Responsive plot

The data in a plot:

```{r}

renderPlot({
  plot_data <- selectedData()
  
  title <- paste0(plot_data$Series[1], " episode ratings")
  ggplot(plot_data) +
    aes(x = OverallEp, y = Rating, color = factor(Season)) +
    geom_point() +
    stat_smooth(method = "lm", formula = y ~ 1, se = FALSE) +
    labs(x = "Overall Episode Number",
         y = "IMDB Rating", 
         color = "Season",
         caption = "Lines: Season averages") +
    ggtitle(title) + 
    expand_limits(y = 7:10) + 
    theme_grey(base_size = 16)  
})

```

### Responsive text

```{r}
# Get the highest rated episode

top_ep <- reactive({
  req(selectedData)
  selectedData() %>%
    arrange(desc(Rating), desc(Votes)) %>%
    head(1)
})
```

The highest rated episode of _`r renderText(top_ep()$Series)`_
is "`r renderText(top_ep()$Episode)`" with a rating of
`r renderText(top_ep()$Rating)` from `r renderText(top_ep()$Votes)` votes.



